### PR TITLE
Convert basic esx scripts for oxmysql

### PR DESCRIPTION
**Pull request by TheSpaceGamerV2**
Hey, i'm not sure everything is good, someone need to review this.

### CODE REVIEW

**Comment by thelindat** [comment]
I ended up not doing this since oxmysql has a mysql-async compatibility file included.

**Comment by TheSpaceGamerV2** [comment]
Well isn't better to convert manually the scripts instead of using the wrapper ?

**Comment by thelindat** [comment]
> Well isn't better to convert manually the scripts instead of using the wrapper ?

See https://github.com/overextended/oxmysql/issues/72

**Comment by TheSpaceGamerV2** [comment]
Ohh okkk, sorry :)

**Pull request closed without merging**
